### ISSUE TITLE
Colab notebook broken?

### ISSUE THREAD

**Issue by lyndond** [AlexanderMath/fasth#1]
Your Colab example doesnt seem to run. Cell #4 throws this error

<img width="763" alt="image" src="https://user-images.githubusercontent.com/8090896/110140091-ba13d280-7da1-11eb-86c3-440a3f8b0413.png">

**Comment by AlexanderMath** [comment]
Thanks for pointing out this mistake, it should be fixed now. Let me know if there are other issues. You might have to refresh or make a new copy of the Colab notebook to get the fixed version. 

![image](https://user-images.githubusercontent.com/8614529/110144668-e139c680-7dd8-11eb-8700-3aef4ef8ddaa.png)

Fun bonus info: I actually wrote the cells to use as pseudo-code for a talk I gave a few months back, the code was never intended to actually run.

**Comment by lyndond** [comment]
Thanks for the quick response! Works like a charm now. Look forward to trying it out in my own models. 

Edit: You'll have to add an ``import time`` in there as well by the way.

**Comment by lyndond** [comment]
I'm going to paste here in case my previous edit gets lost in your notificaitons:

>You'll have to add an ``import time`` in there as well 

Thanks again :)

**Comment by AlexanderMath** [comment]
Haha, nice catch, it's been added :-)
