### ISSUE TITLE
Batched Matrices

### ISSUE THREAD

**Issue by KingJamesSong** [AlexanderMath/fasth#2]
Hi, does the current implementation support batched matrices, i.e., BxNxN instead of NxN ?

**Comment by AlexanderMath** [comment]
I'm not completely sure, but I don't think it will work. When we wrote the cuda code our test cases were for BxN matrices.

That said, we made a new algorithm that reduces the number of sequential operations from O(d/m+m) to O(d/m+lg(m)). Our PyTorch implementation of this algorithm is 2-3x faster that our cuda implementation. I'll add it here as soon as possible, that implementation should work for BxNxN.

**Comment by KingJamesSong** [comment]
Thanks! I just checked current implementation does not support batched matrices.
Look forward to your updates!

**Comment by AlexanderMath** [comment]
@KingJamesSong Sorry for the late reply. 

Please see fasth++ implemented in <a href="https://github.com/AlexanderMath/fasth/blob/master/fasthpp.py" target="_blank">fasthpp.py</a>. 

It seems to work with X.shape=(d,bs) and X.shape=(d,d,bs). Please let me know if you encounter any issues, haven't had the time to thoroughly check everything. If you want a bit more performance you can try to run ```stop_recursion=1,2,3,4,5,6,...``` to see which one is faster on your specific hardware setup.

**Comment by KingJamesSong** [comment]
Hi Alex,

  Sorry for the late reply. I just checked your codes and it seems to work perfectly!
